services:
  unpackflow:
    image: ghcr.io/zaiwuli/unpackflow:latest
    container_name: unpackflow
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      UN_FOLDER_0_PATH: /downloads
      UN_FOLDER_0_EXTRACT_PATH: /output
      UN_FOLDER_0_MOVE_BACK: "true"
      UN_FOLDER_0_DISABLE_LOG: "true"
      UN_FOLDER_0_DELETE_ORIGINAL: "false"
    volumes:
      - /volume2/解压目录/监控目录:/downloads
      - /volume2/解压目录/输出目录:/output
      - /volume2/解压目录/缓存目录:/cache
      - /volume1/CloudNAS/CloudDrive:/volume1/CloudNAS/CloudDrive
      - /volume1/docker/unpackflow:/config
    ports:
      - 8066:5656
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:5656/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
